# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - name: Build and publish Docker Image.
#      uses: mr-smithers-excellent/docker-build-push@v4
#      with:
#        image: cloudstrif/demo-app
#        tag: latest
#        registry: docker.io
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
  build_image:
    needs: build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup GCloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '274.0.1'
        service_account_email: ${{ secrets.GCP_SERVICE_ACCT_EMAIL }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCT_KEY }}
    - run:
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud config set run/region ${{ secrets.GCP_REGION }}
        gcloud auth configure-docker
        gcloud info
    - name: Build and Tag Image
      run: docker build -t "grc.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.APPLICATION_NAME }}:latest" .
    - name: Push to GCP image registry
      run: docker push grc.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.APPLICATION_NAME }}:latest"
    
#  deploy:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#     - run: docker pull cloudstrif/demo-app
