# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  build_image:
    needs: build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Use gcloud CLI
      run: gcloud info
    - run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud config set run/region ${{ secrets.GCP_REGION }}
        gcloud auth configure-docker
        gcloud info
    - name: Build and Tag Image
      run: |
        docker build -t "grc.io/${{ secrets.GCP_PROJECT_ID }}/web-demo:latest" .
        docker tag web-demo:latest "grc.io/${{ secrets.GCP_PROJECT_ID }}/web-demo:latest" 
    - name: Push to GCP image registry
      run: docker push grc.io/${{ secrets.GCP_PROJECT_ID }}/web-demo:latest
    
#  deploy:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#     - run: docker pull cloudstrif/demo-app
