# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: build image
      run: docker build -t cloudstrif/demo-app .
    - name: Buil and publish Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: cloudstrif/demoapp
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
